### ISSUE TITLE
RWS Handling

### ISSUE THREAD

**Issue by Michael21107** [SteveOhByte/Armoury#1]
what happens when this plugin detects enabled RWS?

**Comment by SteveOhByte** [comment]
All RWS-related code is present in Main.cs. If the user has "Disable RWS" set to true via their main configuration file, then Armoury will search the plugins directory for StopThePed's ini. If found, it then finds the line where enable RWS is set to true, and changes the text to false.

**Comment by Michael21107** [comment]
what if one enables RWS when he's already in the game?

**Comment by SteveOhByte** [comment]
In that case Armoury won't be doing anything. The RWS code in Armoury only executes on first plugin load, so if the user decides to run with RWS for a single run it won't be affected until next load, or until the user modifies the config to disable the system.

**Comment by Michael21107** [comment]
so RWS loadout will overwrite the armory's one, right?

**Comment by SteveOhByte** [comment]
Correct, RWS runs a check against the players equipment every few ticks, this is not the case with Armoury. Armoury will only modify the players inventory when requested through the menu or hotkey.

If RWS is enabled, it will always take priority over Armoury.

**Comment by Michael21107** [comment]
is _disable RWS_ on by default?

**Comment by SteveOhByte** [comment]
Yes. I make the assumption that anyone who installs Armoury wants it to be on by default, as otherwise RWS will constantly be wiping the selected Armoury loadout.

**Comment by Michael21107** [comment]
gotcha, the main config file is config.lc?

**Comment by SteveOhByte** [comment]
Yes, it is a plaintext file, as are all the loadout files.

**Comment by Michael21107** [comment]
gotcha, thanks
